// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbo

import (
	"net/netip"
	"time"
)

type Endpoint struct {
	Domain     string    `json:"domain"`
	Method     string    `json:"method"`
	Path       string    `json:"path"`
	Hits       int64     `json:"hits"`
	LastUpdate time.Time `json:"last_update"`
}

type Headline struct {
	ID        int64      `json:"id"`
	CreatedAt time.Time  `json:"created_at"`
	RequestID string     `json:"request_id"`
	Domain    string     `json:"domain"`
	Method    string     `json:"method"`
	Path      string     `json:"path"`
	IP        netip.Addr `json:"ip"`
}

type Request struct {
	ID             int64      `json:"id"`
	CreatedAt      time.Time  `json:"created_at"`
	RequestID      string     `json:"request_id"`
	Domain         string     `json:"domain"`
	Method         string     `json:"method"`
	Path           string     `json:"path"`
	URL            string     `json:"url"`
	IP             netip.Addr `json:"ip"`
	Headers        []byte     `json:"headers"`
	Content        []byte     `json:"content"`
	PartialContent bool       `json:"partial_content"`
}
